TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.01
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.2

  acc_lim_theta: 2.0
  acc_lim_x: 1.0
  acc_lim_y: 1.0

  yaw_goal_tolerance: 0.15
  
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.01

  holonomic_robot: false
  meter_scoring: true
