local_costmap:
   global_frame: map
   robot_base_frame: $(arg base_frame)
   update_frequency: 2.0
   publish_frequency: 1.0
   static_map: false
   rolling_window: true
   width: 4
   height: 4
   resolution: .03
